apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: default
spec:
  releaseName: ingress-nginx
  targetNamespace: default
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 3.6.0
  values:
    fullnameOverride: ingress-nginx
    controller:
      ingressClass: "nginx"
      config:
        "use-forwarded-headers": "true"
      kind: "DaemonSet"
      podAnnotations:
        "prometheus.io/scrape": "true"
        "prometheus.io/port": "10254"
      service:
        enableHttp: "false"
        type: ClusterIP
        annotations:
          cloud.google.com/neg: '{"exposed_ports": {"443":{}}}'
