apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: kube-system
spec:
  values:
    autoDiscovery:
      clusterName: eks-demo-blue
    serviceAccountAnnotations:
      "eks.amazonaws.com/role-arn": arn:aws:iam::062360539084:role/eks-demo-blue-cluster-autoscaler
