apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  releaseName: metrics-server
  targetNamespace: kube-system
  timeout: 300
  resetValues: false
  wait: true
  forceUpgrade: false
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metrics-server
    version: 2.11.2
  values:
    resources:
      requests:
        cpu: "100m"
        memory: "300Mi"
    priorityClassName: "system-cluster-critical"
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1
