apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: default
spec:
  releaseName: nginx-ingress
  targetNamespace: default
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 3.6.0
  values:
    fullnameOverride: ingress-nginx
    controller:
      config:
        "use-forwarded-headers": "true"
      kind: "DaemonSet"
      podAnnotations:
        "prometheus.io/scrape": "true"
        "prometheus.io/port": "10254"
      nodeSelector:
        "node.kubernetes.io/role": "workers"
      service:
        enableHttp: "false"
        externalTrafficPolicy: "Local"
        type: "NodePort"
        nodePorts:
          https: "30443"
          tcp:
            "10254": "32254"
    tcp:
      "10254": "32254"
